# Generated by Django 4.0.4 on 2022-08-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gfc', models.IntegerField()),
                ('eng', models.IntegerField()),
                ('wt1', models.IntegerField()),
                ('bmee', models.IntegerField()),
                ('ampp', models.IntegerField()),
            ],
        ),
    ]
